#![allow(unused)]
use std::{fmt::Display, net::IpAddr, time::Duration};

/// Identifies a process and its executing thread.
///
/// On Linux, a process may contain multiple threads. `pid` identifies the
/// process, while `tid` identifies the specific thread that generated an
/// event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ProcessId {
    /// Process ID (PID).
    pub pid: u32,

    /// Thread ID (TID).
    pub tid: u32,
}

/// Common metadata associated with an event.
///
/// `EventHeader` contains process identity, credentials, timestamp, and
/// command information shared by events emitted by bpfx.
///
/// The timestamp is stored as nanoseconds and can be converted to a
/// [`Duration`] using [`EventHeader::timestamp`].
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[cfg_attr(
    feature = "archive",
    derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct EventHeader {
    /// Event timestamp in nanoseconds.
    pub timestamp_ns: u64,

    /// Process ID (PID) associated with the event.
    pub pid: u32,

    /// Thread ID (TID) associated with the event.
    pub tid: u32,

    /// Parent process ID (PPID).
    pub ppid: u32,

    /// User ID (UID) of the process.
    pub uid: u32,

    /// Group ID (GID) of the process.
    pub gid: u32,

    /// Command name of the process that generated the event.
    pub comm: String,
}

impl Display for EventHeader {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{} pid={} tid={} ppid={} uid={} gid={} comm={}",
            self.timestamp_ns, self.pid, self.tid, self.ppid, self.uid, self.gid, self.comm,
        )
    }
}

impl EventHeader {
    /// Returns the [`ProcessId`] represented by this event header.
    pub fn process(&self) -> ProcessId {
        ProcessId {
            pid: self.pid,
            tid: self.tid,
        }
    }

    /// Returns `true` if the event was generated by a kernel thread.
    ///
    /// Kernel threads are identified by a process ID of `0`.
    pub fn is_kernel_thread(&self) -> bool {
        self.pid == 0
    }

    /// Returns the event timestamp as a [`Duration`].
    ///
    /// The timestamp is interpreted as nanoseconds.
    pub fn timestamp(&self) -> Duration {
        Duration::from_nanos(self.timestamp_ns)
    }
}
